#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import re

# Paths
root = r'c:\Entwicklung\neuer-git-ordner\ki'
german_tools_path = os.path.join(root, 'docs', 'german', 'TOOLS_DOCUMENTATION.md')
german_spec_path = os.path.join(root, 'docs', 'german', 'SPECIALIZATION_PERSISTENCE_SYSTEM.md')
english_tools_path = os.path.join(root, 'docs', 'english', 'TOOLS_DOCUMENTATION.md')
english_spec_path = os.path.join(root, 'docs', 'english', 'SPECIALIZATION_PERSISTENCE_SYSTEM.md')

# Translation dictionary for TOOLS_DOCUMENTATION.md
tools_translations = {
    'ML/KI Integration Status': 'ML/AI Integration Status',
    'Fokus dieser Dokumentation': 'Focus of this documentation',
    'Technische Details der ML/KI-Integration für alle Dashboard-Tools': 'Technical details of ML/AI integration for all dashboard tools',
    'Die User-Dokumentation mit Screenshots und Bedienanleitung befindet sich in': 'User documentation with screenshots and operating instructions is located in',
    'Bedienungsanleitung-KI-Agent.md': 'Operating-Instructions-AI-Agent.md',
    'Zuletzt aktualisiert': 'Last updated',
    '16. Dezember 2025': 'December 16, 2025',
    'Abgeschlossen': 'Complete',
    'Übersicht der Tool-Integration': 'Tool Integration Overview',
    'Kategorie': 'Category',
    'Ja': 'Yes',
    'GESAMT': 'TOTAL',
    'offen': 'pending',
    'Fertiggestellte Tools mit voller ML/KI-Integration': 'Completed Tools with Full ML/AI Integration',
    'Product Management': 'Product Management',
    'Marketing & Content': 'Marketing & Content',
    'Payment & Finances': 'Payment & Finances',
    'Advanced AI': 'Advanced AI',
    'Tools': 'Tools',
    'Status': 'Status',
    'Vollständig': 'Complete',
    'Mit KI-Enhancement': 'With AI enhancement',
    'Integriert': 'Integrated',
    'ML-Features': 'ML Features',
    'API-Integration': 'API Integration',
    'Abhängigkeiten': 'Dependencies',
    'Änderungen': 'Changes',
    'aus ProductBundles extrahiert': 'extracted from ProductBundles',
    'standalone Page mit Dashboard-Tile': 'standalone page with dashboard tile',
    'Fehler-Fixed': 'Bugs Fixed',
    'Neue Features': 'New Features',
    'Character Counter': 'Character Counter',
    'Quick Templates': 'Quick Templates',
    'Last-Saved Timestamp': 'Last-Saved Timestamp',
    'WooCommerce Integration': 'WooCommerce Integration',
    'Backend Endpoint': 'Backend Endpoint',
    'Vollständig implementiert': 'Fully implemented',
    'Rate-limiting Fixes': 'Rate-limiting fixes',
    'OpenAI Description Sanitization': 'OpenAI description sanitization',
    'HTML removal': 'HTML removal',
    '404 Monitoring': '404 monitoring',
    'IP-Block Prevention': 'IP-block prevention',
    'AI-gestützte Produkterstellung mit Optimierung': 'AI-powered product creation with optimization',
    'Automatische Produktdaten-Generierung': 'Automatic product data generation',
    'Intelligente Produktaktualisierung': 'Intelligent product update',
    'Automatische Kategorie-Verwaltung': 'Automatic category management',
    'MLCategorySuggester Integration': 'MLCategorySuggester integration',
    'Automatische Gratis-Produkt-Erstellung': 'Automatic free product creation',
    'MLFreebieGenerator': 'MLFreebieGenerator',
    'Bundle-Erstellung mit KI-Vorschlägen': 'Bundle creation with AI suggestions',
    'Gereinigt': 'Cleaned',
    'ProductAnalysis extrahiert': 'ProductAnalysis extracted',
    'Config-Optionen': 'Config options',
    'Voll funktional mit KI-Toggles': 'Fully functional with AI toggles',
    'KI-basierte Email-Generierung': 'AI-powered email generation',
    'Template-basiert': 'Template-based',
    'LLM-Integration': 'LLM integration',
    'Deutsche Inhalte mit NLP': 'German content with NLP',
    'Automatisierte Kampagnen': 'Automated campaigns',
    'Personalisierung': 'Personalization',
    'Text-to-Speech': 'Text-to-speech',
    'Audio-Generierung': 'Audio generation',
    'Automatisches Content-Posting': 'Automatic content posting',
    'Conversion-Optimization': 'Conversion optimization',
    'Automatische Monetarisierung': 'Automatic monetization',
    'Template-Verwaltung': 'Template management',
    'Design-Vorschläge': 'Design suggestions',
    'SEO-optimierte Blogposts': 'SEO-optimized blog posts',
    'Outline-Generierung': 'Outline generation',
    'Keyword-Analyse': 'Keyword analysis',
    'Content-Struktur': 'Content structure',
    'Bild-Qualitätsprüfung': 'Image quality check',
    'Auto-Tagging': 'Auto-tagging',
    'SEO-Analyse': 'SEO analysis',
    'Vision AI': 'Vision AI',
    'Tag-Generierung': 'Tag generation',
    'Qualitäts-Score': 'Quality score',
    'KI-Kontext-Generierung': 'AI context generation',
    'Mit LLM-Integration': 'With LLM integration',
    'Intelligente String-Generierung': 'Intelligent string generation',
    'Automatische Framework-Implementierung': 'Automatic framework implementation',
    'Mit KI-Enhancement': 'With AI enhancement',
    'Intelligente Daten-Synchronisation': 'Intelligent data synchronization',
    'Mit KI-Optimierung': 'With AI optimization',
    'Fastify backend': 'Fastify backend',
    'WooCommerce API': 'WooCommerce API',
    'Persistent memory für KI-Kontexte': 'Persistent memory for AI contexts',
    'Message-Logging': 'Message logging',
    'Vollständig refaktoriert': 'Fully refactored',
    'useCallback für loadStats/loadMessages': 'useCallback for loadStats/loadMessages',
    'React Hook Dependencies behoben': 'React hook dependencies fixed',
    'useMemo für Message-Filtering': 'useMemo for message filtering',
    'useCallback für API-Calls': 'useCallback for API calls',
    'Statistics Cards': 'Statistics cards',
    'Message Log Table': 'Message log table',
    'Memory Cleanup': 'Memory cleanup',
    'System-Monitoring mit Alerts': 'System monitoring with alerts',
    'buildUrl() normalization': 'buildUrl() normalization',
    'lastUpdated timestamps': 'lastUpdated timestamps',
    'threshold alerts': 'Threshold alerts',
    'Glassmorphism': 'Glassmorphism',
    'Color-coded severity levels': 'Color-coded severity levels',
    'Memory tracking': 'Memory tracking',
    'CPU monitoring': 'CPU monitoring',
    'Service health': 'Service health',
    'KI-gestützte Kundensegmentierung': 'AI-powered customer segmentation',
    'MLPersonalization Integration': 'MLPersonalization integration',
    'Complete TypeScript rewrite': 'Complete TypeScript rewrite',
    'Kacheln-Stats': 'Tile stats',
    'Search/Sort/Filter': 'Search/sort/filter',
    'MLPersonalization modal integration': 'MLPersonalization modal integration',
    'Stats-Cards': 'Statistics cards',
    'Gesamtumsatz': 'Total sales',
    'Ø-Warenkorbwert': 'Average cart value',
    'aktive Kunden': 'Active customers',
    'Top Kunde': 'Top customer',
    'customer status': 'Customer status',
    'last_login': 'Last login',
    'visit_count': 'Visit count',
    'role fields': 'Role fields',
}

def translate_file(input_path, output_path, translations_dict):
    """Read German file and translate to English"""
    print(f"Reading: {input_path}")
    
    with open(input_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    print(f"Original size: {len(content)} characters")
    
    # Apply translations
    for german, english in translations_dict.items():
        content = content.replace(german, english)
    
    print(f"Writing: {output_path}")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Translated size: {len(content)} characters")
    print(f"✓ Successfully translated to {output_path}\n")

# Translate TOOLS_DOCUMENTATION.md
try:
    translate_file(german_tools_path, english_tools_path, tools_translations)
except Exception as e:
    print(f"Error translating TOOLS_DOCUMENTATION.md: {e}")

# For SPECIALIZATION_PERSISTENCE_SYSTEM.md, use a similar approach
spec_translations = {
    'Specialization Persistence & Auto-Load System': 'Specialization Persistence & Auto-Load System',
    'Version': 'Version',
    'Datum': 'Date',
    'Dezember': 'December',
    'Produktiv': 'Production',
    'Auto-Load aktiviert': 'Auto-load activated',
    'Autor': 'Author',
    'Übersicht': 'Overview',
    'Das Specialization Persistence & Auto-Load System ist eine vollständige Lösung für die sichere, persistente Speicherung und automatische Verwaltung von KI-Spezialisierungen': 'The Specialization Persistence & Auto-Load System is a comprehensive solution for secure, persistent storage and automatic management of AI specializations',
    'Filesystem-basierte Persistierung': 'Filesystem-based persistence',
    'mit strukturierter Organisation': 'with structured organization',
    'AES-256-GCM Verschlüsselung': 'AES-256-GCM encryption',
    'für sensible Daten': 'for sensitive data',
    'SHA-256 Integritätschecks': 'SHA-256 integrity checks',
    'für alle gespeicherten Dateien': 'for all stored files',
    'In-Memory Cache': 'In-memory cache',
    'für schnellen Zugriff': 'for fast access',
    'Auto-Load beim Server-Start': 'Auto-load on server startup',
    'mit Fallback-Mechanismen': 'with fallback mechanisms',
    'CRUD-Operationen': 'CRUD operations',
    'für vollständige Verwaltung': 'for complete management',
    'Fehlertoleranz': 'Fault tolerance',
    'mit graceful degradation': 'with graceful degradation',
    'Umfassende Test-Suite': 'Comprehensive test suite',
    '148 Tests passed': '148 tests passed',
    'Architektur': 'Architecture',
    'Komponenten-Übersicht': 'Component Overview',
    'Server Startup': 'Server Startup',
    'Dateisystem-Struktur': 'Filesystem Structure',
    'Verzeichnis-Layout': 'Directory Layout',
    'Globales Inventar aller Spezialisierungen': 'Global inventory of all specializations',
    'Aktive Spezialisierungen pro User': 'Active specializations per user',
    'Fallback-Spezialisierungen': 'Fallback specializations',
    'User-spezifisches Verzeichnis': 'User-specific directory',
    'Spezialisierungs-Daten': 'Specialization data',
    'Metadata & Checksums': 'Metadata & checksums',
    'Sicherheit & Verschlüsselung': 'Security & Encryption',
    'AES-256-GCM Verschlüsselung': 'AES-256-GCM Encryption',
    'Verwendung': 'Usage',
    'Test-Spezialisierungen und Backups': 'Test specializations and backups',
    'Encryption Format': 'Encryption format',
    'encryption format': 'encryption format',
    'Features': 'Features',
    '256-bit Schlüssel für maximale Sicherheit': '256-bit key for maximum security',
    'Unique IV pro Verschlüsselung': 'Unique IV per encryption',
    'verhindert Pattern-Erkennung': 'prevents pattern recognition',
    'Authentication Tag für Tamper-Detection': 'Authentication tag for tamper detection',
    'Original-Hash-Preservation für Integrity-Checks': 'Original hash preservation for integrity checks',
    'SHA-256 Integritätschecks': 'SHA-256 Integrity Checks',
    'Jede gespeicherte Spezialisierung erhält einen SHA-256 Hash': 'Each stored specialization receives a SHA-256 hash',
    'Corruption-Detection beim Laden': 'Corruption detection on load',
    'Vergleich vor/nach Updates': 'Comparison before/after updates',
    'Audit-Trail für Änderungen': 'Audit trail for changes',
    'API & Verwendung': 'API & Usage',
    'Persistence Manager API': 'Persistence Manager API',
    'Initialisierung': 'Initialization',
    'Beim Server-Start': 'On server startup',
    'Spezialisierung persistieren': 'Persist specialization',
    'Spezialisierung laden': 'Load specialization',
    'Aktive Spezialisierung setzen': 'Set active specialization',
    'Aktive Spezialisierung abrufen': 'Get active specialization',
    'Alle Spezialisierungen auflisten': 'List all specializations',
    'Integrität validieren': 'Validate integrity',
    'Spezialisierung löschen': 'Delete specialization',
    'Auto-Load API': 'Auto-Load API',
    'Initialisierung & Cache laden': 'Initialization & load cache',
    'Auto-Load starten': 'Start auto-load',
    'Aktive Spezialisierung aus Cache': 'Get active specialization from cache',
    'synchron': 'synchronous',
    'schnell': 'fast',
    'Loading-State prüfen': 'Check loading state',
    'Spezialisierung aktivieren': 'Activate specialization',
    'Updated cache & disk': 'Updates cache & disk',
    'Cache neu laden': 'Reload cache',
    'Cache invalidated & reloaded': 'Cache invalidated & reloaded',
    'Alle validieren': 'Validate all',
    'Verfügbare auflisten': 'List available',
    'State-Management': 'State Management',
    'Loading States': 'Loading States',
    'Initial State': 'Initial state',
    'Lädt von Disk': 'Loading from disk',
    'Cache Invalidation': 'Cache Invalidation',
    'Der Cache wird invalidiert bei': 'The cache is invalidated by',
    'Explizites Reload': 'Explicit reload',
    'Neue Aktivierung': 'New activation',
    'Komplett neu geladen': 'Completely reloaded',
    'Testing': 'Testing',
    'Test-Suite Übersicht': 'Test Suite Overview',
    'Gesamt': 'Total',
    'passed': 'passed',
    'skipped': 'skipped',
    'failed': 'failed',
    'Persistence Tests': 'Persistence Tests',
    'Datei': 'File',
    'Coverage': 'Coverage',
    'Initialisierung & Setup': 'Initialization & setup',
    'Persist & Load-Operationen': 'Persist & load operations',
    'Active/Fallback-Mechanismen': 'Active/fallback mechanisms',
    'Listing & Inventar': 'Listing & inventory',
    'Integrity-Validierung': 'Integrity validation',
    'Delete-Operationen': 'Delete operations',
    'Corruption-Recovery': 'Corruption recovery',
    'Error-Handling': 'Error handling',
    'Auto-Load Tests': 'Auto-Load Tests',
    'Persistence-Suite': 'Persistence suite',
    'Cache-Funktionalität': 'Cache functionality',
    'State-Transitions': 'State transitions',
    'Activation & Reload': 'Activation & reload',
    'Validation': 'Validation',
    'Missing-Data-Handling': 'Missing data handling',
    'Backup Manager Tests': 'Backup Manager Tests',
    'Load & List Operationen': 'Load & list operations',
    'Encryption & Decryption': 'Encryption & decryption',
    'Hash-Generierung & Consistency': 'Hash generation & consistency',
    'Integrity-Checks': 'Integrity checks',
    'Error-Recovery': 'Error recovery',
    'Performance': 'Performance',
    '< 100ms per operation': '< 100ms per operation',
    'Encryption Flow Tests': 'Encryption Flow Tests',
    'Encrypt → Save → Load → Decrypt': 'Encrypt → save → load → decrypt',
    'Unicode & Special Characters': 'Unicode & special characters',
    'Large Prompts': 'Large prompts',
    'Edge Cases': 'Edge cases',
    'empty values': 'empty values',
    'Performance & Statistics': 'Performance & statistics',
    'Test-Execution': 'Test Execution',
    'Alle Tests': 'All tests',
    'Nur Persistence': 'Persistence only',
    'Nur Auto-Load': 'Auto-load only',
    'Nur Encryption': 'Encryption only',
    'Performance': 'Performance',
    'Benchmarks': 'Benchmarks',
    'Setup': 'Setup',
    'Spezialisierungen': 'Specializations',
    'Windows 11': 'Windows 11',
    'Node.js': 'Node.js',
    'Durchschnitt': 'Average',
    'Maximum': 'Maximum',
    'Load Single': 'Load single',
    'Persist': 'Persist',
    'List All': 'List all',
    'Validate Integrity': 'Validate integrity',
    'Auto-Load Initialize': 'Auto-load initialize',
    'Cache Hit': 'Cache hit',
    'Encryption': 'Encryption',
    'Decryption': 'Decryption',
    'Optimierungen': 'Optimizations',
    'In-Memory Cache': 'In-memory cache',
    'Vermeidet wiederholte Disk-Reads': 'Avoids repeated disk reads',
    'Lazy Loading': 'Lazy loading',
    'Metadata wird nur bei Bedarf geladen': 'Metadata loaded only when needed',
    'Batch Operations': 'Batch operations',
    'Validierung nutzt Promise.all': 'Validation uses Promise.all',
    'Async File-I/O': 'Async file I/O',
    'Blockiert nicht den Event-Loop': 'Does not block the event loop',
    'Troubleshooting': 'Troubleshooting',
    'Problem': 'Problem',
    'Spezialisierung nicht gefunden': 'Specialization not found',
    'Symptom': 'Symptom',
    'Lösung': 'Solution',
    'Prüfe ob Datei existiert': 'Check if file exists',
    'Validiere index.json': 'Validate index.json',
    'Prüfe Logs auf Corruption-Warnings': 'Check logs for corruption warnings',
    'Corrupted File': 'Corrupted file',
    'Unexpected token': 'Unexpected token',
    'Prüfe `.meta.json` Checksum': 'Check `.meta.json` checksum',
    'Restore aus Fallback': 'Restore from fallback',
    'nutzt automatisch Fallback': 'automatically uses fallback',
    'Neuanlage falls nötig': 'Recreate if necessary',
    'Cache out-of-sync': 'Cache out-of-sync',
    'Cache zeigt alte Daten nach Update': 'Cache shows old data after update',
    'Auto-Load failed State': 'Auto-load failed state',
    'Prüfe Logs für Root-Cause': 'Check logs for root cause',
    'Retry mit': 'Retry with',
    'Fallback prüfen': 'Check fallback',
    'gibt immer etwas zurück': 'always returns something',
    'Best Practices': 'Best Practices',
    'Immer initialize() aufrufen': 'Always call initialize()',
    'Gut': 'Good',
    'Schlecht': 'Bad',
    'Kann fehlschlagen': 'Can fail',
    'Errors gracefully behandeln': 'Handle errors gracefully',
    'Spec nicht gefunden': 'Spec not found',
    'nutze Fallback': 'using fallback',
    'Kann crashen': 'Can crash',
    'Cache nutzen für häufige Zugriffe': 'Use cache for frequent access',
    'Synchron': 'Synchronous',
    'Aber langsamer': 'But slower',
    'Disk-Read': 'Disk read',
    'Regelmäßig validieren': 'Validate regularly',
    'Täglich oder bei kritischen Operationen': 'Daily or before critical operations',
    'Corrupted specs detected': 'Corrupted specs detected',
    'Fallbacks definieren': 'Define fallbacks',
    'Beim Setup': 'During setup',
    'Wird automatisch als Fallback verwendet wenn active fehlt': 'Automatically used as fallback if active fails',
    'Verwandte Dokumentation': 'Related Documentation',
    'Upload & Security': 'Upload & security',
    'Test-Daten': 'Test data',
    'Security-Overview': 'Security overview',
    'System-Architektur': 'System architecture',
    'Support': 'Support',
    'Bei Fragen oder Problemen': 'For questions or problems',
    'Prüfe Logs': 'Check logs',
    'Validiere System': 'Validate system',
    'Konsultiere diese Dokumentation': 'Consult this documentation',
    'Kontaktiere Development Team': 'Contact development team',
    'Letzte Aktualisierung': 'Last Updated',
    'Produktiv & Getestet': 'Production & tested',
}

try:
    translate_file(german_spec_path, english_spec_path, spec_translations)
except Exception as e:
    print(f"Error translating SPECIALIZATION_PERSISTENCE_SYSTEM.md: {e}")

print("\n✓ Translation complete!")
