#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os

# Extended translation dictionary - comprehensive
translations = {
    # Common German terms
    'Fokus': 'Focus',
    'Technische Details': 'Technical details',
    'Zuletzt aktualisiert': 'Last updated',
    'Status': 'Status',
    'Abgeschlossen': 'Complete',
    'Übersicht': 'Overview',
    'Kategorie': 'Category',
    'Ja': 'Yes',
    'GESAMT': 'TOTAL',
    'offen': 'pending',
    'Fertiggestellte Tools': 'Completed tools',
    'voller ML/KI-Integration': 'full ML/AI integration',
    'ML-Features': 'ML Features',
    'API-Integration': 'API Integration',
    'Abhängigkeiten': 'Dependencies',
    'Änderungen': 'Changes',
    'Fehler-Fixed': 'Bugs Fixed',
    'Neue Features': 'New Features',
    'Character Counter': 'Character Counter',
    'Quick Templates': 'Quick Templates',
    'Last-Saved Timestamp': 'Last-Saved Timestamp',
    'WooCommerce Integration': 'WooCommerce Integration',
    'Backend Endpoint': 'Backend Endpoint',
    'Vollständig': 'Complete',
    'Integriert': 'Integrated',
    'refaktoriert': 'refactored',
    'Vollständig implementiert': 'Fully implemented',
    'Vollständig refaktoriert': 'Fully refactored',
    'Rate-limiting': 'Rate-limiting',
    'OpenAI': 'OpenAI',
    'Description': 'Description',
    'HTML': 'HTML',
    'IP-Block Prevention': 'IP-block prevention',
    'AI-gestützte Produkterstellung': 'AI-powered product creation',
    'Automatische Produktdaten-Generierung': 'Automatic product data generation',
    'Intelligente Produktaktualisierung': 'Intelligent product update',
    'Automatische Kategorie-Verwaltung': 'Automatic category management',
    'Automatische Gratis-Produkt-Erstellung': 'Automatic free product creation',
    'Bundle-Erstellung': 'Bundle creation',
    'KI-Vorschlägen': 'AI suggestions',
    'Gereinigt': 'Cleaned',
    'Config-Optionen': 'Config options',
    'Voll funktional': 'Fully functional',
    'KI-Toggle': 'AI toggles',
    'KI-basierte Email-Generierung': 'AI-powered email generation',
    'Template-basiert': 'Template-based',
    'LLM-Integration': 'LLM integration',
    'Deutsche Inhalte': 'German content',
    'Automatisierte Kampagnen': 'Automated campaigns',
    'Personalisierung': 'Personalization',
    'Text-to-Speech': 'Text-to-speech',
    'Audio-Generierung': 'Audio generation',
    'Automatisches Content-Posting': 'Automatic content posting',
    'Conversion-Optimization': 'Conversion optimization',
    'Automatische Monetarisierung': 'Automatic monetization',
    'Template-Verwaltung': 'Template management',
    'Design-Vorschläge': 'Design suggestions',
    'SEO-optimierte Blogposts': 'SEO-optimized blog posts',
    'Outline-Generierung': 'Outline generation',
    'Keyword-Analyse': 'Keyword analysis',
    'Content-Struktur': 'Content structure',
    'Bild-Qualitätsprüfung': 'Image quality check',
    'Auto-Tagging': 'Auto-tagging',
    'SEO-Analyse': 'SEO analysis',
    'Vision AI': 'Vision AI',
    'Tag-Generierung': 'Tag generation',
    'Qualitäts-Score': 'Quality score',
    'KI-Kontext-Generierung': 'AI context generation',
    'Intelligente String-Generierung': 'Intelligent string generation',
    'Automatische Framework-Implementierung': 'Automatic framework implementation',
    'Intelligente Daten-Synchronisation': 'Intelligent data synchronization',
    'KI-Optimierung': 'AI optimization',
    'Fastify backend': 'Fastify backend',
    'Persistent memory': 'Persistent memory',
    'KI-Kontexte': 'AI contexts',
    'Message-Logging': 'Message logging',
    'useCallback': 'useCallback',
    'React Hook': 'React hook',
    'useMemo': 'useMemo',
    'Statistics Cards': 'Statistics cards',
    'Message Log Table': 'Message log table',
    'Memory Cleanup': 'Memory cleanup',
    'System-Monitoring': 'System monitoring',
    'buildUrl()': 'buildUrl()',
    'Glassmorphism': 'Glassmorphism',
    'Color-coded': 'Color-coded',
    'Memory tracking': 'Memory tracking',
    'CPU monitoring': 'CPU monitoring',
    'Service health': 'Service health',
    'KI-gestützte Kundensegmentierung': 'AI-powered customer segmentation',
    'Complete TypeScript': 'Complete TypeScript',
    'Search/Sort/Filter': 'Search/sort/filter',
    'Stats-Cards': 'Statistics cards',
    'Gesamtumsatz': 'Total sales',
    'Warenkorbwert': 'Cart value',
    'aktive Kunden': 'Active customers',
    'Top Kunde': 'Top customer',
    'Feedback Analysis': 'Feedback Analysis',
    'Sentiment-Analyse': 'Sentiment analysis',
    'Automatische Kategorisierung': 'Automatic categorization',
    'Impact-Bewertung': 'Impact assessment',
    'KI-generierte': 'AI-generated',
    'Recommendations': 'Recommendations',
    'Criticality-Levels': 'Criticality levels',
    'WooCommerce Reviews': 'WooCommerce reviews',
    'Support-Tickets': 'Support tickets',
    'KI-Analyse': 'AI analysis',
    'Reviews + Tickets': 'Reviews + tickets',
    'Sentiment Detection': 'Sentiment detection',
    'Pattern Recognition': 'Pattern recognition',
    'Insight-Grid': 'Insight grid',
    'PLUGIN-ANFORDERUNG': 'PLUGIN REQUIREMENT',
    'Awesome Support': 'Awesome Support',
    'WordPress Application': 'WordPress application',
    'REST-Endpunkt': 'REST endpoint',
    'Authentifizierung': 'Authentication',
    'Basis-Auth': 'Basic auth',
    'Ticket-Daten': 'Ticket data',
    'echten Support-Tickets': 'real support tickets',
    'Setup': 'Setup',
    'Installiere das Plugin': 'Install the plugin',
    'Aktiviere das Plugin': 'Activate the plugin',
    'Stelle sicher': 'Ensure',
    'Umgebungsvariablen': 'Environment variables',
    'Backend-Start': 'Backend start',
    'deine WordPress-Installation': 'Your WordPress installation',
    'Falls das Plugin nicht verfügbar ist': 'If the plugin is not available',
    'aussagekräftige Fehlermeldung': 'Meaningful error message',
    'Ticket-Abruf': 'Ticket retrieval',
    'Review-Analyse': 'Review analysis',
    'funktioniert weiterhin': 'continues to work',
    'WooCommerce kommen': 'from WooCommerce',
    'Mock-Daten': 'Mock data',
    'Fallback-Tickets': 'Fallback tickets',
    'Real Web Analytics': 'Real Web Analytics',
    'Multi-Source Trend': 'Multi-source trend',
    'Google Trends': 'Google Trends',
    'Reddit': 'Reddit',
    'News': 'News',
    'GitHub': 'GitHub',
    'StackOverflow': 'StackOverflow',
    'KI-Report Generation': 'AI-powered report generation',
    'GPT-basierter Analyse': 'GPT-based analysis',
    'Confidence Scoring': 'Confidence scoring',
    'Top Trend Detection': 'Top trend detection',
    'Batch Product': 'Batch product',
    'Time-Range': 'Time-range',
    'Multi-Source': 'Multi-source',
    'Trend Scoring': 'Trend scoring',
    'Source-Level': 'Source-level',
    'Analytic Regioning': 'Analytic Regioning',
    'KI-Regionen-Analyse': 'AI-powered region analysis',
    'regionale Performance': 'Regional performance',
    'KI-Score': 'AI-score',
    'Confidence-Scoring': 'Confidence scoring',
    'Regionen-spezifische': 'Region-specific',
    'Global/Europa/Amerika/Asien': 'Global/Europe/Americas/Asia',
    'Top-Performer': 'Top performers',
    'Optimierungsbedarf': 'Optimization needs',
    'Regional Traffic': 'Regional traffic',
    'Country Performance': 'Country performance',
    'Top Countries': 'Top countries',
    'Premium Audit': 'Premium Audit',
    'KI-gestützte Shop-Optimierung': 'AI-powered shop optimization',
    'Audit-Kategorien': 'Audit categories',
    'Cost-Benefit-Analyse': 'Cost-benefit analysis',
    'Prioritätsvergabe': 'Priority assignment',
    'Kategorie-spezifische': 'Category-specific',
    'Optimierungsvorschläge': 'Optimization suggestions',
    'Standard Audit': 'Standard Audit',
    'KI-gestützte Quick-Checks': 'AI-powered quick checks',
    'Basis-Audit-Checks': 'Basic audit checks',
    'Schnelle KI': 'Quick AI',
    'Importance-based': 'Importance-based',
    'Progress Tracking': 'Progress tracking',
    'Quick-Fix Detection': 'Quick-fix detection',
    'Next Steps Generation': 'Next steps generation',
    'Mini Audit': 'Mini Audit',
    'Trend Analysis': 'Trend Analysis',
    'KI-gestützte Trend-Analyse': 'AI-powered trend analysis',
    'Summary-Generation': 'Summary generation',
    'Mock-Fallback': 'Mock fallback',
    'Run Trend Analysis': 'Run Trend Analysis',
    'Progressives KI': 'Progressive AI',
    'Insight-Mapping': 'Insight mapping',
    'Ergebnis-Rendering': 'Result rendering',
    'Simulated Fallback': 'Simulated fallback',
    'Fortschrittsanzeige': 'Progress display',
    'Real Analytics': 'Real Analytics',
    'Echtzeit-ML': 'Real-time ML',
    'Auto-Refresh': 'Auto-refresh',
    'Realtime-Pipeline': 'Real-time pipeline',
    'Basic-APIs': 'Basic APIs',
    'begrenzte': 'limited',
    'Shop Metrics': 'Shop Metrics',
    'Conversion Analysis': 'Conversion Analysis',
    'Conversion Reported': 'Conversion Reported',
    'Shop Health Report': 'Shop Health Report',
    'Payment & Finances': 'Payment & Finances',
    'VOLLSTÄNDIG ML/KI-INTEGRIERT': 'COMPLETE ML/AI INTEGRATION',
    'PaymentFinances': 'PaymentFinances',
    'Payment Fast': 'Payment Fast',
    'Fraud Detection': 'Fraud detection',
    'Auto-Check': 'Auto-check',
    'Smart Amount': 'Smart amount',
    'Risk Scoring': 'Risk scoring',
    'Payment Simplified': 'Payment Simplified',
    'Simplified Payment': 'Simplified payment',
    'ML-Optimization': 'ML optimization',
    'Payment Tester': 'Payment Tester',
    'ML-Testplan-Generator': 'ML test plan generator',
    'KI-Diagnose': 'AI diagnosis',
    'MLPaymentAnalyzer': 'MLPaymentAnalyzer',
    'Payment Verifier': 'Payment Verifier',
    'ML-basierte': 'ML-based',
    'Transaction': 'Transaction',
    'Verification': 'Verification',
    'Risk Level': 'Risk level',
    'low/medium/high/critical': 'Low/medium/high/critical',
    'Payment Success': 'Payment Success',
    'Success Metrics': 'Success metrics',
    'Feature-basierte': 'Feature-based',
    'Event-Tracking': 'Event tracking',
    'Payment Validation': 'Payment Validation',
    'KI-gestützte Security': 'AI-powered security',
    'Analysis': 'Analysis',
    'Pattern Detection': 'Pattern detection',
    'Payment Issued': 'Payment issued',
    'Issue Detection': 'Issue detection',
    'Auto-Categorization': 'Auto-categorization',
    'Payment User Favor': 'Payment User Favor',
    'GPT-4o-mini': 'GPT-4o-mini',
    'Personalization': 'Personalization',
    'Datenschutz-Hinweis': 'Data protection notice',
    'Payment Delivery': 'Payment Delivery',
    'Delivery Analytics': 'Delivery analytics',
    'Payment Emergency': 'Payment Emergency',
    'KI-Notfall-Analyse': 'AI emergency analysis',
    'Payment Expansion': 'Payment Expansion',
    'KI-Expansionsplan': 'AI expansion plan',
    'Confidence & Projection': 'Confidence & projection',
    'Payment Quick Check': 'Payment Quick Check',
    'KI Quick-Scan': 'AI quick scan',
    'Avg Confidence': 'Average confidence',
    'ML Payment Analyzer': 'ML Payment Analyzer',
    'Dedicated ML': 'Dedicated ML',
    'Analyzer Component': 'Analyzer component',
    'Datenschutz-Compliance': 'Data protection compliance',
    'DSGVO-Hinweise': 'GDPR notices',
    'OpenAI-API-Transparenz': 'OpenAI API transparency',
    '30-Tage-Retention': '30-day retention',
    'RAM-only': 'RAM-only',
    'Processing': 'Processing',
    'Recent Updates': 'Recent updates',
    'Fixes & Improvements': 'Fixes & Improvements',
    'KRITISCHE FIXES': 'CRITICAL FIXES',
    'Rate-Limiting Protection': 'Rate-Limiting Protection',
    'useEffect Dependency': 'useEffect dependency',
    'Hell führte': 'led',
    'Infinite API': 'Infinite API',
    'Calls': 'calls',
    'buildUrl aus': 'buildUrl from',
    'useEffect Dependencies': 'useEffect dependencies',
    'Products laden': 'Products load',
    'nur beim Mount': 'only on mount',
    'AbortController': 'AbortController',
    'Request-Deduplication': 'Request deduplication',
    'Loading-State schützt': 'Loading state prevents',
    'parallelen Requests': 'Parallel requests',
    'Impact': 'Impact',
    'Verhindert': 'Prevents',
    'OpenAI Rate-Limiting': 'OpenAI rate-limiting',
    'API-Quota-Erschöpfung': 'API quota exhaustion',
    'Commit': 'Commit',
    'OpenAI Description': 'OpenAI description',
    'Overflow Fix': 'Overflow fix',
    'ungefilter Descriptions': 'Unfiltered descriptions',
    'Shortcodes': 'Shortcodes',
    'Token-Explosion': 'Token explosion',
    'Descriptions werden': 'Descriptions are',
    'sanitized': 'Sanitized',
    'HTML entfernt': 'HTML removed',
    'Shortcodes gelöscht': 'Shortcodes deleted',
    'Max 500 Zeichen': 'Max 500 character',
    'Limit pro Beschreibung': 'Limit per description',
    'OpenAI-Crashes': 'OpenAI crashes',
    'Token-Overspending': 'Token overspending',
    'Shop bleibt stabil': 'Shop stays stable',
    'Keine Crashes': 'No crashes',
    'großen Datenmengen': 'Large data amounts',
    'Bitpalast IP-Block': 'Bitpalast IP-block',
    'IP 213.138.57.94': 'IP 213.138.57.94',
    'blockiert': 'blocked',
    'zu vielem 404-Traffic': 'Excessive 404 traffic',
    'Hacker-Scan': 'Hacker scan',
    'setNotFoundHandler': 'setNotFoundHandler',
    'server.ts': 'server.ts',
    'loggt ALLE 404': 'Logs all 404s',
    'IP + Method': 'IP + method',
    'Frontend erkennt': 'Frontend recognizes',
    'explizit 404/503': 'Explicitly 404/503',
    'Fehler': 'errors',
    'Silent Failures': 'Silent failures',
    'Retry-Spam': 'Retry spam',
    'Weniger Blockeys': 'Fewer blocks',
    'Hostinganbietern': 'Hosting providers',
    'besseres Debugging': 'Better debugging',
    'TypeScript Compilation': 'TypeScript compilation',
    'trends-routes.ts': 'trends-routes.ts',
    'fehlende 500-Response': 'Missing 500-response',
    'Schema Definition': 'Schema definition',
    'Hinzufügen von': 'Adding',
    'Swagger-Schema': 'Swagger schema',
    'Backend kompiliert': 'Backend compiles',
    'sauber': 'cleanly',
    'Duplicate Handler Fix': 'Duplicate handler fix',
    'Zwei': 'Two',
    'setNotFoundHandler Calls': 'setNotFoundHandler calls',
    'handler already set': 'Handler already set',
    'Error': 'error',
    'Gemerged in': 'Merged into',
    'unified 404-Handler': 'Unified 404 handler',
    '404-Monitoring': '404 monitoring',
    'SPA-Fallback': 'SPA fallback',
    'Server startet': 'Server starts',
    'ohne Fehler': 'without errors',
    'Product Notes': 'Product notes',
    'Feature mit': 'feature with',
    'Enhancements': 'enhancements',
    'POST': 'POST',
    'Speicherung': 'Storage',
    'meta_data': 'Meta_data',
    'Schlüssel': 'Key',
    'notes': 'Notes',
    'Regal 5B': 'Shelf 5B',
    'Lieferant bestellt': 'Supplier ordered',
    'Ankunft erwartet': 'Arrival expected',
    'Mängel vorhanden': 'Defects found',
    'Grüner Checkmark': 'Green checkmark',
    'Uhrzeit': 'Time',
    'Lagerort': 'Storage location',
    'Warehouse': 'Warehouse',
    'Lagerort-Informationen': 'Storage location information',
    'Speichern nach': 'Save after',
    'Sekunden Inaktivität': 'Seconds of inactivity',
    'Button-Klick': 'Button click',
    'nötig': 'needed',
    '0/1000 Zeichen': '0/1000 characters',
    'Warnungen': 'Warnings',
    'orange >70%': 'Orange >70%',
    'rot >90%': 'Red >90%',
    'schnelle Buttons': 'Quick buttons',
    'häufige Notizen': 'Common notes',
    'Visuelles Feedback': 'Visual feedback',
    'Persistent Storage': 'Persistent storage',
    'Daten bleiben': 'Data persists',
    'erhalten': 'remain',
    'Initial Notes': 'Initial notes',
    'Autosave + Counter': 'Autosave + counter',
    'Templates': 'Templates',
    'ML Settings': 'ML Settings',
    'Zweck': 'Purpose',
    'Konfiguration': 'Configuration',
    'GET/POST': 'GET/POST',
    'Funktional': 'Functional',
    'Config-Verwaltung': 'Config management',
    'Feature-Toggles': 'Feature toggles',
    'Modell-Auswahl': 'Model selection',
    'Root Dashboard': 'Root dashboard',
    'AIDashboard': 'AIDashboard',
    'Voll funktional': 'Fully functional',
    'Struktur': 'Structure',
    'Kategorien': 'Categories',
    'insgesamt': 'total',
    'Category Filtering': 'Category filtering',
    'all/analytics/products/payments/marketing/advanced': 'All/analytics/products/payments/marketing/advanced',
    'Tool Cards': 'Tool cards',
    'Icons': 'Icons',
    'Descriptions': 'Descriptions',
    'Direct Navigation': 'Direct navigation',
    'Real Dashboard': 'Real dashboard',
    'Sales': 'Sales',
    'Orders': 'Orders',
    'Conversion': 'Conversion',
    'Customers': 'Customers',
    'Sales Chart': 'Sales chart',
    'Framer Motion': 'Framer motion',
    'Animations': 'Animations',
    'Navigation Pattern': 'Navigation pattern',
    'pageUrl führt': 'pageUrl leads',
    'direkt zu': 'directly to',
    'Tool-Seite': 'Tool page',
    'API-Calls': 'API calls',
    'Navigation nötig': 'Navigation needed',
    'Refresh Mechanism': 'Refresh mechanism',
    '30-Sekunden': '30-second',
    'Interval': 'Interval',
    'Hintergrund-Updates': 'Background updates',
    'Loading-Spinner': 'Loading spinner',
    'Zusammenfassung': 'Summary',
    'Status je': 'Status by',
    'Bereich': 'Area',
    'ABGESCHLOSSEN & FERTIG': 'COMPLETE & READY',
    'Bedarf Upgrade': 'Needs upgrade',
    'Nächste Schritte': 'Next steps',
    'TODO-Liste': 'TODO list',
    'PRIORITÄT 1': 'PRIORITY 1',
    'HIGH': 'HIGH',
    'Werden am meisten': 'Most frequently',
    'verwendet': 'used',
    'Analytics Tools': 'Analytics tools',
    'Implementiere': 'Implement',
    'AI-Recommendations': 'AI recommendations',
    'ConversionAnalysis': 'ConversionAnalysis',
    'ML-Ausbau': 'ML expansion',
    'ShopMetrics': 'ShopMetrics',
    'ConversionReported': 'ConversionReported',
    'ShopHealthReport': 'ShopHealthReport',
    'Budget': 'Budget',
    'Tage': 'Days',
    'Payment Tools': 'Payment tools',
    'von': 'of',
    'upgrade': 'upgrade',
    'Fraud Detection': 'Fraud detection',
    'System': 'System',
    'Payment': 'Payment',
    'Pattern Recognition': 'Pattern recognition',
    'Payment': 'Payment',
    'Smart Routing': 'Smart routing',
    'PRIORITÄT 2': 'PRIORITY 2',
    'MEDIUM': 'MEDIUM',
    'Nice-to-have': 'Nice-to-have',
    'API Endpoint': 'API endpoint',
    'Documentation': 'Documentation',
    'Performance': 'Performance',
    'Optimization': 'Optimization',
    'Lazy Loading': 'Lazy loading',
    'Analytics': 'Analytics',
    'Caching Strategy': 'Caching strategy',
    'häufig genutzte': 'frequently used',
    'Metriken': 'Metrics',
    'PRIORITÄT 3': 'PRIORITY 3',
    'LOW': 'LOW',
    'Maintenance': 'Maintenance',
    'Einheitliche Error': 'Unified error',
    'Handling': 'Handling',
    'Tools': 'Tools',
    'Loading States': 'Loading states',
    'Standardisierung': 'Standardization',
    'Toast Notification': 'Toast notification',
    'System': 'System',
    'Vereinheitlichung': 'Unification',
    'API Endpoints': 'API endpoints',
    'Referenz': 'Reference',
    'Analytics': 'Analytics',
    'GET': 'GET',
    'POST': 'POST',
    'Dashboard': 'Dashboard',
    'Shop-Metriken': 'Shop metrics',
    'Conversion-Daten': 'Conversion data',
    'Feedback-Analyse': 'Feedback analysis',
    'Trend-Testing': 'Trend testing',
    'Trend-/Realtime-Analysis': 'Trend/real-time analysis',
    'Products': 'Products',
    'Product-Analyse': 'Product analysis',
    'Auto-Produkt-Erstellung': 'Auto product creation',
    'WooCommerce-Integration': 'WooCommerce integration',
    'Product Notes': 'Product notes',
    'Speichern': 'Saving',
    'NEU': 'NEW',
    'Payments': 'Payments',
    'ML Payment': 'ML payment',
    'Metrics': 'Metrics',
    'Payment-Verarbeitung': 'Payment processing',
    'Marketing': 'Marketing',
    'Email-Generierung': 'Email generation',
    'Blogpost-Generierung': 'Blogpost generation',
    'Bild-Analyse': 'Image analysis',
    'Advanced': 'Advanced',
    'Memory-Statistiken': 'Memory statistics',
    'Memory-Messages': 'Memory messages',
    'System-Health': 'System health',
    'ML-Konfiguration': 'ML configuration',
    'Statistik': 'Statistics',
    'Gesamt': 'Total',
    'Vollständig': 'Complete',
    'integriert': 'integrated',
    'Teilweise': 'Partially',
    'Minimal': 'Minimal',
    'Keine Integration': 'No integration',
    'Kategorie-Übersicht': 'Category Overview',
    'teilweise': 'Partial',
    'Verwandte Dokumentation': 'Related Documentation',
    'User-Bedienung': 'User operation',
    'Deployment': 'Deployment',
    'ML-Setup': 'ML setup',
    'BACKEND_AI_SETUP.md': 'BACKEND_AI_SETUP.md',
    'Architecture': 'Architecture',
    'Autor': 'Author',
    'André Zabel': 'André Zabel',
    'Aktualisiert': 'Updated',
    'Repository': 'Repository',
    'Artificial': 'Artificial',
    'Retail': 'Retail',
    'Intelligence': 'Intelligence',
    'System': 'System',
    'Session Summary': 'Session Summary',
    'Fokus': 'Focus',
    'Bug Fixes': 'Bug fixes',
    'Product Notes': 'Product notes',
    'Enhancement': 'Enhancement',
    'Alle Fehler': 'All bugs',
    'behoben': 'Fixed',
    'neue Features': 'New features',
    'produktiv': 'productive',
    'Gelöste Issues': 'Resolved issues',
    'Infinite Loop': 'Infinite loop',
    'Dependencies': 'Dependencies',
    'Token Overflow': 'Token overflow',
    'Sanitization': 'Sanitization',
    'IP-Blocks': 'IP blocks',
    'Hoster': 'Hosting provider',
    'Monitoring': 'Monitoring',
    'TypeScript': 'TypeScript',
    'Compilation': 'Compilation',
    'Schema': 'Schema',
    'Validation': 'Validation',
    'Server': 'Server',
    'Startup': 'Startup',
    'Duplicate': 'Duplicate',
    'Handler': 'Handler',
    'Neue Features': 'New features',
    'Notes-Feld': 'Notes field',
    'Lagerort': 'Storage',
    'Warehouse-Info': 'Warehouse info',
    'Autosave': 'Autosave',
    'Sekunden': 'seconds',
    'Counter': 'Counter',
    'Timestamps': 'Timestamps',
    'Builds Status': 'Build status',
    'Frontend': 'Frontend',
    'npm run build': 'npm run build',
    'Exit': 'Exit',
    'Backend': 'Backend',
    'Läuft': 'Running',
    'ohne': 'without',
    'Fehler': 'errors',
    'All Routes': 'All routes',
    'registriert': 'Registered',
    'erfolgreich': 'Successfully',
}

def translate_content(content):
    """Translate all German terms to English"""
    for german, english in translations.items():
        # Use whole word matching with word boundaries where applicable
        content = content.replace(german, english)
    return content

# File paths
root = r'c:\Entwicklung\neuer-git-ordner\ki'
files_to_translate = [
    ('docs\\english\\TOOLS_DOCUMENTATION.md', 'TOOLS_DOCUMENTATION.md'),
    ('docs\\english\\SPECIALIZATION_PERSISTENCE_SYSTEM.md', 'SPECIALIZATION_PERSISTENCE_SYSTEM.md'),
]

for file_path, name in files_to_translate:
    full_path = os.path.join(root, file_path)
    print(f"\nProcessing: {name}")
    print(f"Path: {full_path}")
    
    if os.path.exists(full_path):
        try:
            # Read
            with open(full_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            original_size = len(content)
            
            # Translate
            content = translate_content(content)
            
            new_size = len(content)
            
            # Write
            with open(full_path, 'w', encoding='utf-8') as f:
                f.write(content)
            
            print(f"✓ Translated successfully")
            print(f"  Original: {original_size} chars -> New: {new_size} chars")
        except Exception as e:
            print(f"✗ Error: {e}")
    else:
        print(f"✗ File not found: {full_path}")

print("\n\n✓ All translations complete!")
